/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rpggame.adventure.paths.hermitpath;

import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import rpggame.adventurer.Adventurer2;
import static rpggame.adventurer.Adventurer2.user;

/**
 *
 * @author Mikey
 */
public class Hermit3 extends javax.swing.JFrame {

    /**
     * Creates new form Hermit3
     */
    public Hermit3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orcImage = new javax.swing.JLabel();
        hermitImg = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        ctc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        orcImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpggame/adventure/paths/hermitpath/Orc.png"))); // NOI18N

        hermitImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpggame/adventure/paths/hermitpath/181-1818011_samurai-sheet-enemies-metal-slug-huge-hermit-pixel-art2.png"))); // NOI18N
        hermitImg.setText("jLabel1");

        text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text.setText("PLACEHOLDER");
        text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textMouseClicked(evt);
            }
        });

        ctc.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        ctc.setForeground(new java.awt.Color(0, 0, 0));
        ctc.setText("(Click to Continue)");
        ctc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ctc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctcMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orcImage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ctc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(hermitImg, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(hermitImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orcImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ctcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctcMouseClicked
        if(p == 2){
            trickCont();
        }
    }//GEN-LAST:event_ctcMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(p == 2){
            trickCont();
        }
    }//GEN-LAST:event_formMouseClicked

    private void textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMouseClicked
        if(p == 2){
            trickCont();
        }
    }//GEN-LAST:event_textMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hermit3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hermit3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hermit3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hermit3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hermit3().setVisible(true);
            }
        });
    }
    
    int p = 0;
    int[] path = user().getPath();
    public void contPath(){
        switch(path[3]){
            case 1:
                negotiate();
                p = 1;
                break;
            case 2:
                trick();
                p = 2;
                break;
            default:
                System.out.println("uh oh");
                break;
        }
    }
    
    public void negotiate(){
        setTitle("You negotiate with them");
        hermitImg.setVisible(true);
        orcImage.setVisible(true);
        ctc.setVisible(false);
        text.setText(String.format("<html><body style=\"text-align: justify;  text-justify: inter-word;"
                + "\">%s</body></html>","Thank you so much " + new Adventurer2().user().getName() + ", we've decided we will split the cave instead of"
                        + " fighting!"));
        setVisible(true);
    }
    
    public void trick(){
        setVisible(true);
        hermitImg.setVisible(false);
        int r = ThreadLocalRandom.current().nextInt(0, 10 + 1);
        System.out.println(r);
        if(r >= 5){
            ctc.setVisible(false);
            text.setText(String.format("<html><body style=\"text-align: justify;  text-justify: inter-word;"
                + "\">%s</body></html>","The orc believes you, and leaves the cave. Well done."));
        }else{
            text.setText(String.format("<html><body style=\"text-align: justify;  text-justify: inter-word;"
                + "\">%s</body></html>","The orc does not believe you, and begins to fight you."));
            
        }
    }
    
    public void trickCont(){
        ctc.setVisible(false);
        int r = ThreadLocalRandom.current().nextInt(0, 10 + 1);
        if(r >= 5){
            text.setText(String.format("<html><body style=\"text-align: justify;  text-justify: inter-word;"
                + "\">%s</body></html>","You lost the glorious battle to the orc, better luck next time."));
        }else{
            text.setText(String.format("<html><body style=\"text-align: justify;  text-justify: inter-word;"
                + "\">%s</body></html>","You won the battle against the orc, well done."));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ctc;
    private javax.swing.JLabel hermitImg;
    private javax.swing.JLabel orcImage;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
